import type { AppProps } from 'next/app';
import { ReactElement, ReactNode } from 'react';
import DefaultLayout from '../components/Layouts/DefaultLayout';
import { Provider } from 'react-redux';
import store from '../store/index';
import Head from 'next/head';

// Perfect Scrollbar
import 'react-perfect-scrollbar/dist/css/styles.css';

import '../styles/tailwind.css';
import { NextPage } from 'next';
import { useRouter } from 'next/router';
import BlankLayout from '@/components/Layouts/BlankLayout';

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
   getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
   Component: NextPageWithLayout;
};

const App = ({ Component, pageProps }: AppPropsWithLayout) => {
   const router = useRouter();

   const getLayout =
      Component.getLayout ??
      ((page) => {
         if (router.pathname.startsWith('/admin') || router.pathname.startsWith('/member')) {
            return <DefaultLayout>{page}</DefaultLayout>;
         } else {
            return <BlankLayout>{page}</BlankLayout>;
         }
      });

   return (
      <Provider store={store}>
         <Head>
            <title>VRISTO - Multipurpose Tailwind Dashboard Template</title>
            <meta charSet="UTF-8" />
            <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/assets/images/logo.svg" />
         </Head>

         {getLayout(<Component {...pageProps} />)}
      </Provider>
   );
};
export default App;
